import type { Metadata } from "next";
import "./globals.css";
import ClientErrorBoundary from "@/components/ClientErrorBoundary";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head></head>
      <body>
        <div className="container mx-auto mt-10 px-6">
          <ClientErrorBoundary pageTitle="Oops! Something went wrong">
            {children}
          </ClientErrorBoundary>
        </div>
      </body>
    </html>
  );
}

